### ISSUE TITLE
Bug: Undefined method `date' for nil

### ISSUE THREAD

**Issue by CarlosLugones** [maybe-finance/maybe#1245] opened 2024-10-05 10:43 UTC
**Describe the bug**

This seems to happen on a null field, related to Rails.

https://stackoverflow.com/questions/39983657/rails-undefined-method-date-for-nilnilclass

**To Reproduce**
1. Login
2. Go to dashboard homepage
3. Go to a bank account details page
4. Unknown issue occurred.

**Screenshots / Recordings**

![image](https://github.com/user-attachments/assets/3302bc05-6328-4127-9116-ed2f469caabd)

![image](https://github.com/user-attachments/assets/1c65aed7-8edd-406f-b228-488bb3574592)

**Additional context**

Version: v0.1.0-alpha.17

**Comment by zachgoll** [comment] 2024-10-07 13:34
@CarlosLugones thanks for the report.  Can you share any relevant logs or account details for this that could help us identify the root cause?

**Comment by LingkKang** [comment] 2024-10-08 00:18
Try you can reload the page, it works for me.

**Comment by zachgoll** [comment] 2024-10-23 21:37
I'm unable to get this reproduced and I believe this may have been fixed as part of the many account sync updates we've made recently.

Going to close this issue for now.  If we can identify the root of this, happy to reopen and fix.

**Closed by zachgoll** 2024-10-23 21:37 UTC
Labels: :bug: Bug
