### ISSUE TITLE
Bug: Institution Images do not show up

### ISSUE THREAD

**Issue by 825i** [maybe-finance/maybe#1149] opened 2024-09-03 11:14 UTC
**Describe the bug**
After adding a new institution the icons/images you choose for it do not display after the instance is restarted.

**To Reproduce**
1. Add a new institution
2. Upload an image for it
3. Reload the instance
4. Image placeholder shows a broken image

**Expected behavior**
The image should stay working after Maybe instance is reloaded/restarted.

Maybe version: v0.1.0-alpha.16

**Screenshots / Recordings**

![image](https://github.com/user-attachments/assets/449f23eb-25b3-4596-bb7a-6cde6ba9d743)

![image](https://github.com/user-attachments/assets/a9741b45-cb26-4a2b-9ad9-d89795e7c500)

**Additional context**
For some reason I get a 404 error on self-hosted instance. Here is the URL:

```
https://maybe.mysite.com/rails/active_storage/disk/eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJkeTRndWw2dHQ2ZjA5dTcxYWhnOGU1Zm93cTlnIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwiT1BfRmluYW5jaWFsX0dyb3VwLnBuZ1wiOyBmaWxlbmFtZSo9VVRGLTgnJ09QX0ZpbmFuY2lhbF9Hcm91cC5wbmciLCJjb250ZW50X3R5cGUiOiJpbWFnZS9wbmciLCJzZXJ2aWNlX25hbWUiOiJsb2NhbCJ9LCJleHAiOiIyMDI0LTA5LTAzVDExOjEwOjIwLjM0MVoiLCJwdXIiOiJibG9iX2tleSJ9fQ==--967282d012776a49355e8318d34a9902f56ec065/bankicon.png
HTTP ERROR 404
```

**Comment by zachgoll** [comment] 2024-09-13 15:29
Closing as I cannot reproduce this.  Feel free to comment with more information and I can reopen!

**Comment by 825i** [comment] 2024-09-19 19:49
No custom configuration whatsoever. I am merely using the same docker image that is made by you guys. Absolutely no changes at all except adding my API key when asked for currency conversion.

**Comment by 825i** [comment] 2024-09-19 19:51
This is what I get in the logs. If this is not how the PNG files are meant to be accessed, how are they meant to be accessed? Beacuse the logs are pretty clear that it is trying to source the files and can't find them.

```
I, [2024-09-19T22:48:41.882960 #1]  INFO -- : [2c431e8c-145c-49e2-9c28-fe760e947a21] Redirected to https://mb.xtu.icu/rails/active_storage/disk/eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJrbml1eTZqaHBnbnMwY3ozamRvamJidnBsZjdnIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwidW5uYW1lZCAlMjgxJTI5LnBuZ1wiOyBmaWxlbmFtZSo9VVRGLTgnJ3VubmFtZWQlMjAlMjgxJTI5LnBuZyIsImNvbnRlbnRfdHlwZSI6ImltYWdlL3BuZyIsInNlcnZpY2VfbmFtZSI6ImxvY2FsIn0sImV4cCI6IjIwMjQtMDktMTlUMTk6NTM6NDEuODgyWiIsInB1ciI6ImJsb2Jfa2V5In19--7dcf0005436f13f08ebc858e5ef956b433106ac9/unnamed%20(1).png
I, [2024-09-19T22:48:41.883010 #1]  INFO -- : [2c431e8c-145c-49e2-9c28-fe760e947a21] Completed 302 Found in 1ms (ActiveRecord: 0.1ms (1 query, 0 cached) | GC: 0.0ms)
I, [2024-09-19T22:48:41.951948 #1]  INFO -- : [b2967197-9183-4c73-9418-53a70fba649b] Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiIwejhvMTlqaG5uOG1jazd1NDlrendpa255c2JrIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwidW5uYW1lZC5wbmdcIjsgZmlsZW5hbWUqPVVURi04Jyd1bm5hbWVkLnBuZyIsImNvbnRlbnRfdHlwZSI6ImltYWdlL3BuZyIsInNlcnZpY2VfbmFtZSI6ImxvY2FsIn0sImV4cCI6IjIwMjQtMDktMTlUMTk6NTM6NDEuODc0WiIsInB1ciI6ImJsb2Jfa2V5In19--5ae51665f8467be18d42a1e8d00eff14b117f67b/unnamed.png" for 91.154.112.75 at 2024-09-19 22:48:41 +0300
I, [2024-09-19T22:48:41.952847 #1]  INFO -- : [b2967197-9183-4c73-9418-53a70fba649b] Processing by ActiveStorage::DiskController#show as PNG
I, [2024-09-19T22:48:41.953138 #1]  INFO -- : [b2967197-9183-4c73-9418-53a70fba649b]   Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"unnamed"}
I, [2024-09-19T22:48:41.953078 #1]  INFO -- : [db469fc9-f5f3-413e-bc02-d5f6f1164bff] Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJrbml1eTZqaHBnbnMwY3ozamRvamJidnBsZjdnIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwidW5uYW1lZCAlMjgxJTI5LnBuZ1wiOyBmaWxlbmFtZSo9VVRGLTgnJ3VubmFtZWQlMjAlMjgxJTI5LnBuZyIsImNvbnRlbnRfdHlwZSI6ImltYWdlL3BuZyIsInNlcnZpY2VfbmFtZSI6ImxvY2FsIn0sImV4cCI6IjIwMjQtMDktMTlUMTk6NTM6NDEuODgyWiIsInB1ciI6ImJsb2Jfa2V5In19--7dcf0005436f13f08ebc858e5ef956b433106ac9/unnamed%20(1).png" for 91.154.112.75 at 2024-09-19 22:48:41 +0300
I, [2024-09-19T22:48:41.956971 #1]  INFO -- : [db469fc9-f5f3-413e-bc02-d5f6f1164bff] Processing by ActiveStorage::DiskController#show as PNG
I, [2024-09-19T22:48:41.957062 #1]  INFO -- : [db469fc9-f5f3-413e-bc02-d5f6f1164bff]   Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"unnamed (1)"}
I, [2024-09-19T22:48:41.955640 #1]  INFO -- : [b2967197-9183-4c73-9418-53a70fba649b] Completed 404 Not Found in 2ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)
I, [2024-09-19T22:48:41.957313 #1]  INFO -- : [db469fc9-f5f3-413e-bc02-d5f6f1164bff] Completed 404 Not Found in 0ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)
I, [2024-09-19T22:48:41.962342 #1]  INFO -- : [d1d3feb4-68ee-4bac-a46f-4ecb23739b22] Started GET "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6IjQxOWFkNDBkLTIzMDUtNGQ1Ny1hZWJhLTE3OGRhNTJjZjRlMiIsInB1ciI6ImJsb2JfaWQifX0=--23ba85f130c6332ddf7492a1b8ed7b3d07b1d874/images2.png" for 91.154.112.75 at 2024-09-19 22:48:41 +0300
I, [2024-09-19T22:48:41.962604 #1]  INFO -- : [d1d3feb4-68ee-4bac-a46f-4ecb23739b22] Processing by ActiveStorage::Blobs::RedirectController#show as PNG
I, [2024-09-19T22:48:41.962634 #1]  INFO -- : [d1d3feb4-68ee-4bac-a46f-4ecb23739b22]   Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsiZGF0YSI6IjQxOWFkNDBkLTIzMDUtNGQ1Ny1hZWJhLTE3OGRhNTJjZjRlMiIsInB1ciI6ImJsb2JfaWQifX0=--23ba85f130c6332ddf7492a1b8ed7b3d07b1d874", "filename"=>"images2"}
I, [2024-09-19T22:48:41.964198 #1]  INFO -- : [d1d3feb4-68ee-4bac-a46f-4ecb23739b22] Redirected to https://mb.xtu.icu/rails/active_storage/disk/eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJ2M2Jud2ZrNXF0Y3Z2amhoaGNrNGtkOXQwYm1kIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwiaW1hZ2VzMi5wbmdcIjsgZmlsZW5hbWUqPVVURi04JydpbWFnZXMyLnBuZyIsImNvbnRlbnRfdHlwZSI6ImltYWdlL3BuZyIsInNlcnZpY2VfbmFtZSI6ImxvY2FsIn0sImV4cCI6IjIwMjQtMDktMTlUMTk6NTM6NDEuOTYzWiIsInB1ciI6ImJsb2Jfa2V5In19--24c228733710dbee13bfe7469a1e33b22dc08a2b/images2.png
I, [2024-09-19T22:48:41.964252 #1]  INFO -- : [d1d3feb4-68ee-4bac-a46f-4ecb23739b22] Completed 302 Found in 2ms (ActiveRecord: 0.1ms (1 query, 0 cached) | GC: 0.0ms)
I, [2024-09-19T22:48:42.039857 #1]  INFO -- : [6bab906c-cedb-4885-8cfa-cbbc65c395b3] Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJ2M2Jud2ZrNXF0Y3Z2amhoaGNrNGtkOXQwYm1kIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwiaW1hZ2VzMi5wbmdcIjsgZmlsZW5hbWUqPVVURi04JydpbWFnZXMyLnBuZyIsImNvbnRlbnRfdHlwZSI6ImltYWdlL3BuZyIsInNlcnZpY2VfbmFtZSI6ImxvY2FsIn0sImV4cCI6IjIwMjQtMDktMTlUMTk6NTM6NDEuOTYzWiIsInB1ciI6ImJsb2Jfa2V5In19--24c228733710dbee13bfe7469a1e33b22dc08a2b/images2.png" for 91.154.112.75 at 2024-09-19 22:48:42 +0300
I, [2024-09-19T22:48:42.040460 #1]  INFO -- : [6bab906c-cedb-4885-8cfa-cbbc65c395b3] Processing by ActiveStorage::DiskController#show as PNG
I, [2024-09-19T22:48:42.040527 #1]  INFO -- : [6bab906c-cedb-4885-8cfa-cbbc65c395b3]   Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"images2"}
I, [2024-09-19T22:48:42.041533 #1]  INFO -- : [6bab906c-cedb-4885-8cfa-cbbc65c395b3] Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | GC: 0.0ms)
```

**Comment by zachgoll** [comment] 2024-09-20 00:48
@825i can you do the following for me so we can narrow this down?

- Upgrade to latest Maybe instance
- Attempt to re-upload a new PNG and confirm the bug
- Post the specs of the machine you're running on, including:
  - OS
  - Docker version 
- Post your `compose.yml` file (be sure to mask any sensitive data)

**Comment by vanhalt** [comment] 2024-09-28 08:07
This seems to be an issue with host user's permission and volumes. I had a similar error (that I have not bothered to fix) because the  `Dockerfile` specifies an user (rails:rails) and my `docker` instance is running as root.

If you check your logs you'll see something like:

```
# failed to save my profile image
...7-86beb7857043]   Disk Storage (0.6ms) Downloaded file from key: 8kf23kbq6b0mh1cg......
ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError):
[91af7c43-c24f-425c-8b47-86beb7857043] 
Causes:
[91af7c43-c24f-425c-8b47-86beb7857043] Errno::ENOENT 
(No such file or directory @ rb_sysopen - /rails/storage/8k/f2/8kf23kbq6b0mh1cg4xtge2ea1ac0)
....
```

So check: 

- host, docker process user and docker container user
- volumes and their permissions

**Comment by mgirouard** [comment] 2024-10-02 03:40
@vanhalt is probably right here. 

I always bind mount my volumes instead of using docker volumes to make backups easier. I ran into this as well and can confirm that it was indeed permissions on the mounted volume; specifically in the `maybe` service. On your host machine, you can run:

```bash
$ sudo chmod -R 1000 path/to/data
``` 
Where `1000` is the user ID in the [Dockerfile](https://github.com/maybe-finance/maybe/blob/v0.1.0-alpha.17/Dockerfile#L57), and `path/to/data` is the path you specify in the `volumes` for the service.

You'll need to be careful though: you only want to do this on the volume for the rails app. If you mount your postgres data, you will want to leave that as-is.

I don't think this is a bug. It's just docker and permissions can get weird.

**Comment by zachgoll** [comment] 2024-10-02 12:13
I think @vanhalt and @mgirouard are correct here.  We had a similar permissions issue come up in the past, which led me to update the example docker compose file in this PR:

https://github.com/maybe-finance/maybe/pull/950

Using Docker's named volumes should solve this for most users.

I'll re-open if that's not the case.

**Closed by zachgoll** 2024-10-02 12:13 UTC
Labels: :bug: Bug
