### ISSUE TITLE
Bug: Cant add Holding

### ISSUE THREAD

**Issue by MrTob** [maybe-finance/maybe#1533] opened 2024-12-12 19:00 UTC
**Describe the bug**
Adding a Holding to an Investment/Brokerage Account is not possibe

**To Reproduce**
1. Create an Account (Investment/Brokerage)
2. Click on add Holding
3. Fill out the fields
4. See the error in the console

**Expected behavior**
Adding should work

**What version of Maybe are you using?**
self-hosted: v0.2.0-alpha.2

**What operating system and browser are you using?**
Win11 Chrome

**Screenshots / Recordings**
![chrome_4RAURKSui9](https://github.com/user-attachments/assets/74be419d-98c1-4943-84d2-b3ad79d17ec8)

![chrome_5mp8EYIEj3](https://github.com/user-attachments/assets/41f7812d-da24-413a-9b47-40158c75031b)

**Comment by zachgoll** [comment] 2024-12-12 20:10
@MrTob the console error does not appear to be related to Maybe.

Can you try this in an incognito browser / different browser and see if it still throws the error?

Also, make sure you're updated to latest commit as there have been changes to this form very recently.

**Comment by MrTob** [comment] 2024-12-12 20:40
Image is `image: ghcr.io/maybe-finance/maybe:latest`
Tried it with Firefox/incognito tab. Still the same

https://github.com/user-attachments/assets/954040e3-4e56-492e-b28f-03ad1524ff77

**Comment by zachgoll** [comment] 2024-12-13 18:35
@MrTob thanks for the recording.

Could you provide the exact Firefox version that you're using?  My hunch is that you're on an older version that doesn't support the `crypto.randomUUID` function, which is [somewhat new](https://caniuse.com/mdn-api_crypto_randomuuid).

This bug is not directly caused by the Maybe app, but is actually being called in HotwireCombobox: 

https://github.com/josefarias/hotwire_combobox/blob/57ee6c9087320fab9383a07fa919fe75e0ea72ba/app/assets/javascripts/hw_combobox/models/combobox/callbacks.js#L12

cc @josefarias, not sure if you're looking to support older browsers, but tagging you just in case!

**Comment by josefarias** [comment] 2024-12-13 18:40
Ah yes, we've had reports of `crypto.randomUUID` not working in non-secure (i.e. non-https) contexts as well so that's another thing to check.

I _am_ planning to replace it with something that'll work everywhere. But my general recommendation is to stick to secure contexts and updated browsers.

**Comment by zachgoll** [comment] 2024-12-13 18:45
@josefarias sounds good!  

@MrTob I'm going to close this issue out and defer to Jose's recommendation for now as there is nothing that we can do on the Maybe side for this.

**Closed by zachgoll** 2024-12-13 18:45 UTC
Labels: :bug: Bug, :information_source: Needs info

**Comment by MrTob** [comment] 2024-12-14 08:48
Thanks for looking into this. I would like to point out an important consideration for self-hosted scenarios:
I may be running on a local network (like home environments). I think this is a common use case, and requiring HTTPS adds unnecessary complexity to these setups. While HTTPS is critical for public deployments, requiring it for local network installations creates an additional barrier for users who want to self-hosted Maybe privately. Making this work smoothly in local environments would greatly improve the self-hosting experience.

**Comment by zachgoll** [comment] 2024-12-16 20:33
@MrTob no problem!  I see your point, but unfortunately we have no control over this on the Maybe side.  This would need to be implemented on the HotwireCombobox repo.

**Comment by MrTob** [comment] 2024-12-18 09:06
FYI: I’ve added a Traefik container as a reverse proxy for the MaybeOS application. So far, it seems like this solution is working (using a custom certificate). For anyone in a similar situation: Traefik makes it relatively straightforward to integrate self-signed or Let’s Encrypt certificates, which can help meet HTTPS requirements even in local network setups.

**Comment by josefarias** [comment] 2024-12-31 02:08
Fixed in `hotwire_combobox`'s `main` as of https://github.com/josefarias/hotwire_combobox/commit/b827048a8305e1115d5f96931ba1c9750d1e59fc

Will be part of the next release!
