### ISSUE TITLE
Bug: Average cost of investment provided and used are different

### ISSUE THREAD

**Issue by chetanjain2099** [maybe-finance/maybe#1528] opened 2024-12-10 12:18 UTC
**Describe the bug**
Average cost of investment for the share that I provided and the the average cost that it use is different. This is happening with all the shares.

**To Reproduce**
1. Go to Investment Account
2. Click on New Transaction
3. Add a new transaction with any values.
4. Go to Holding page. Click on the share. 

**Expected behavior**
Average cost of investment for the share that I provided and the the average cost that it uses should be same.

**What version of Maybe are you using?**
Self-Hosted version v0.2.0-alpha.2

**Screenshots:**
![image](https://github.com/user-attachments/assets/b559989a-aba5-4c09-974a-ad8b53b87808)

**Comment by zachgoll** [comment] 2024-12-10 15:04
This is a duplicate of #1087, which should be implemented this week.

**Closed by zachgoll** 2024-12-10 15:04 UTC
Labels: :bug: Bug

**Comment by chetanjain2099** [comment] 2024-12-12 06:51
Hi,

That is not what I was talking about.

Look at the image below. The two highlighted value should be same, right?
![IMG_1858](https://github.com/user-attachments/assets/fea52ea7-451e-4677-851b-224b22bf7d43)

**Comment by zachgoll** [comment] 2024-12-16 20:36
@chetanjain2099 that's my bad!  Misread the original description.  This has been fixed on `main`.
