### ISSUE TITLE
Bug: Multicurrency Support

### ISSUE THREAD

**Issue by igbanam-stripe** [maybe-finance/maybe#784] opened 2024-05-21 08:52 UTC
**Where did this bug occur?**

- [x] Local development
- [ ] Self hosted app (i.e. Docker)

**Describe the bug**

Selecting a base currency filters out all other accounts in the net worth; and calculates the total balance wrong.

**To Reproduce**
1. Create two accounts in two different currencies
2. Notice only one account's balance is the net worth on the dashboard
3. Go to `Settings > Preferences > Currency` and select the other account's currency
4. Notice the net worth changes to the balance of the other account

**Expected behavior**
I expected the net worth / balance to be calculated based on the selected currency.

**Screenshots / Recordings**

In the dashboard…

<img width="1518" alt="Maybe_and_Aditya_Rajan__DM__-_Stripe_-_8_new_items_-_Slack" src="https://github.com/maybe-finance/maybe/assets/162343243/3c3478d7-0b21-4db3-97d0-60d388b56900">

&nbsp;

In the Accounts Settings page…

<img width="1510" alt="Maybe" src="https://github.com/maybe-finance/maybe/assets/162343243/e1f2abb0-5a9c-4020-9f46-31d247ba0334">

&nbsp;

**Additional context**
n/a

**Comment by zachgoll** [comment] 2024-05-21 13:56
Thanks for the bug report!  This appears to be a duplicate of #724 so I'm going to close it out.

The reason the totals do not align is because you have not setup exchange rates yet, which is the mechanism that converts and rolls everything up.  Our documentation and UI for this is very lacking right now, so #724 is aimed to address this and make it clearer to the user what is going on and how to fix it.

**Closed by zachgoll** 2024-05-21 13:56 UTC
Labels: :bug: Bug, :rocket: Feature

**Comment by Aubermean** [comment] 2024-07-21 18:50
In terms of making clearer to user how to fix it, basically, you need to sign up for an API key and add it to your .env file for currency sync to work.

 https://github.com/maybe-finance/maybe?tab=readme-ov-file#multi-currency-support
