### ISSUE TITLE
Bug: Not all investment accounts support Plaid's "liabilities" item type

### ISSUE THREAD

**Issue by smcpeck** [maybe-finance/maybe#1557] opened 2024-12-19 02:15 UTC
**Describe the bug**
Adding an investment account via Plaid can result in the following:
![image](https://github.com/user-attachments/assets/963ac96d-3506-4126-aa04-9c97875d0282)

**Logs:**
```
Error fetching get_item_liabilities for item 03e0dfdb-a247-474d-bb54-eba93d475202: Error message: the server returns an error
HTTP status code: 400
Response headers: {"server"=>"nginx", "date"=>"Thu, 19 Dec 2024 01:59:37 GMT", "content-type"=>"application/json; charset=utf-8", "content-length"=>"264", "connection"=>"keep-alive", "content-encoding"=>"gzip", "plaid-version"=>"2020-09-14", "vary"=>"Accept-Encoding"}
```
```json
Response body: {
  "display_message": null,
  "documentation_url": "https://plaid.com/docs/?ref=error#item-errors",
  "error_code": "PRODUCTS_NOT_SUPPORTED",
  "error_message": "the following products are not supported by this institution: [\"liabilities\"]",
  "error_type": "ITEM_ERROR",
  "request_id": "en4vPjYbtwIbWTN",
  "suggested_action": null
}
```

When this happens, the account balance is sync'd, but the holdings are not fully reflected.

**To Reproduce**
1. Add an investment account that does not support the "liabilities" item via Plaid's API.
2. Observe generic error in the UI.
3. Notice detailed error in the logs.

**Expected behavior**
Account should sync properly.

**What version of Maybe are you using?**
Self-hosted. v0.2.0

**Additional context**
This was noticed on accounts with multiple institutions.

**Comment by zachgoll** [comment] 2024-12-19 15:00
@smcpeck this is expected behavior.  Our Plaid sync gracefully handles this product errors because it is the only way we can find out whether an institution supports that product.

The "Error occurred while syncing data" is caused by something else, which should be available in the `error` column of the `syncs` table.

**Comment by smcpeck** [comment] 2024-12-19 15:13
Thanks, @zachgoll  -- learning these things is a big help to be able to provide some better information.

The only error I see in my `syncs` table is the following:
> undefined method `dig' for nil

I feel like I have seen this discussed somewhere... maybe I just need a more recent build of the container image, but I am on `latest` and re-pulled at some point yesterday.

**Comment by zachgoll** [comment] 2024-12-19 15:40
@smcpeck `undefined method `dig` for nil` is definitely the root cause of this sync "failure".

We are still working on adding better observability for syncs so we can get more info than just that.  In our production app we use Sentry which allows us to pinpoint these root causes a lot easier and another reason we're not supporting Plaid officially for self-hosted instances.  It's just a lot harder to track these things down when we don't have any idea what's happening on your server.

**Comment by smcpeck** [comment] 2024-12-19 15:41
Looking at the code a bit, it seems like this `.dig()` method is applied to Synth API responses. Given that my Synth credits were chewed up after adding 2 accounts, it looks like I am dead in the water until that resets.

**Comment by smcpeck** [comment] 2024-12-19 15:46
Thanks for the quick responses, @zachgoll.

I know y'all are as busy as you can be... if there is ever some extra pieces put in place for the local dev environment or self-hosted compose file to enabled better observability, I am happy to poke around a bit more. As my ruby chops are non-existent, it is difficult for me otherwise... maybe just some `TRACE` logging could help so we get a lot of verbosity in the logs.

Anyway... feel free to close this for now if you'd like.  🍻

**Comment by zachgoll** [comment] 2024-12-19 15:56
@smcpeck I agree with you that we could probably have a bit better logging for self hosted instances since "syncs" apply to more than just Plaid instances—they apply to all accounts.

I'll go ahead and close this one out, but I've opened up a new issue to target this exact improvement:

https://github.com/maybe-finance/maybe/issues/1559

**Closed by zachgoll** 2024-12-19 15:56 UTC
Labels: :bug: Bug, :information_source: Needs info
