### ISSUE TITLE
Impossible to click on buttons during onboarding

### ISSUE THREAD

**Issue by jadiaheno** [maybe-finance/maybe#139] opened 2024-01-18 12:27 UTC
**Describe the bug**
Not possible to click on buttons during the onboarding

**To Reproduce**

After updating your .env, launch the app.
Signup with a brand new account.
There is an onboarding  screen. It's impossible to click on any button. Navigation with the keyboard works.

**Expected behavior**
I expected to select the next button with clicks

**Screenshots**
https://github.com/maybe-finance/maybe/assets/13062328/e98a0b2a-77b2-4014-bb5c-4faa5eaf82be

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser: Edge, chrome, safari
-   Version 121.0.2277.49

**Comment by Shpigford** [comment] 2024-01-18 13:34
This has been reported a couple of times in Discord. It appears to be a z-index issue, but the problem is it seems almost random. I haven't been able to duplicate it.

Here's a Discord thread of others having the problem: https://discord.com/channels/1191501936281784361/1196856336235901049

**Comment by yannickmathey** [comment] 2024-01-18 14:27
I have a similar issue but only the final "Finish" button is not clickable (thought all inputs are filled). I'm going to explore deeper this issue to see if it's really related to this one

**Comment by areyeslo** [comment] 2024-01-20 02:13
Do not have any issues using Chrome or Edge:
https://app.screencastify.com/v3/watch/7QjvecsAShG5U9tGfr6i

**Comment by gmwill934** [comment] 2024-01-22 02:44
I can take a look at this

**Comment by tmyracle** [comment] 2024-01-25 03:43
@jadiaheno I just pushed a fix for this I think, it was hard to reproduce and was sporadic so let me know if pulling the latest from main works for you.

**Comment by tmyracle** [comment] 2024-01-28 18:14
Closing for now, please feel free to open another issue if this is encountered again.

**Closed by tmyracle** 2024-01-28 18:14 UTC
Labels: bug, help wanted, high priority
