### ISSUE TITLE
Bug: Maybe fails catastrophically when using "Å" character in account name

### ISSUE THREAD

**Issue by 825i** [maybe-finance/maybe#1091] opened 2024-08-15 06:46 UTC
**Describe the bug**
Seems latin dialectics cause Maybe to fail.

**To Reproduce**
1. Make a new account
2. Use **Å, å, Ä, ä, Ö, ö**, etc. in the name
3. Save the account
4. Maybe crashes with 502 error
5. Maybe never recovers from said error

**Expected behavior**
Maybe should be able to handle dialectics.

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/74c1a124-50f6-4194-bdaa-e6d8f753aa3d)

**Additional context**
Happening on my current self-hosted instance. Error is reproducible.

**Comment by zachgoll** [comment] 2024-08-15 17:24
@825i I'm not able to reproduce this myself:

https://github.com/user-attachments/assets/629aa236-6ab7-4362-baf6-6e6ed05eb5ea

That said, in #1086 I pushed a fix for an error that was causing accounts to crash like this and I believe that is more likely why this has happened.

Would you mind rebooting your Render instance manually and see if that fixes things?

**Closed** 2024-08-23 14:30 UTC
Labels: :bug: Bug, :information_source: Needs info

**Comment by 825i** [comment] 2024-09-19 19:52
It works fine now. I think you fixed it.
