### ISSUE TITLE
Bug: File 406-unsupported-browser.html does not exist

### ISSUE THREAD

**Issue by g-nogueira** [maybe-finance/maybe#700] opened 2024-05-01 17:43 UTC
**Describe the bug**
Just finished up installing maybe on Render following the steps. Clecked on the link to open that app and came across `We're sorry, but something went wrong.`. Then I looked into the logs and found the real error.

> I, [2024-05-01T17:32:41.011544 #123]  INFO -- : [1b3e46a5-d1ca-47f2-a7f2-d1a372b9d898] Completed 500 Internal Server Error in 3ms (ActiveRecord: 0.0ms (0 queries, 0 cached) | Allocations: 520)
E, [2024-05-01T17:32:41.014757 #123] ERROR -- : [1b3e46a5-d1ca-47f2-a7f2-d1a372b9d898]   
[1b3e46a5-d1ca-47f2-a7f2-d1a372b9d898] ArgumentError (File /opt/render/project/src/public/406-unsupported-browser.html does not exist):

**To Reproduce**
1. Follow the steps from [Self Hosting Maybe on Render](https://github.com/maybe-finance/maybe/blob/main/docs/self-hosting/render.md)
2. Still from the manual, click on the "custom URL in the format `https://maybe-abcd.onrender.com`"
4. Wait for the page to load and see the error

**Expected behavior**
The real error message "Your browser is not supported". And some additional info on the logs to understand why the browser isn't supported.

**Screenshots / Recordings**
![image](https://github.com/maybe-finance/maybe/assets/27465604/af5ee8c4-90eb-42b3-8e15-04a86a109cea)

**Additional context**
Browser: Floorp - based on Firefox
On Chrome and Edge it works

**Comment by zachgoll** [comment] 2024-05-01 18:47
@g-nogueira thanks for the report!  Going to close this as it is a duplicate of #637 as you mentioned.

**Closed by zachgoll** 2024-05-01 18:47 UTC
Labels: :bug: Bug
