### ISSUE TITLE
Bug: Unable to use hostname as DB_HOST

### ISSUE THREAD

**Issue by Tymec** [maybe-finance/maybe#730] opened 2024-05-08 22:14 UTC
**Describe the bug**
I am unable to use a hostname for the `DB_HOST` env variable, while using `localhost` or any valid IP address works. When the container starts, it successfully creates the `maybe_production` database in postgres, but crashes after the "Booting Puma" line.

**To Reproduce**
Followed the docker compose setup and set `DB_HOST=db`. Additionally I set the postgres container hostname to `db`.

docker-compose.yaml:
```yaml
services:
  app:
    image: ghcr.io/maybe-finance/maybe:latest
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: true
      com.centurylinklabs.watchtower.monitor-only: true
    ports:
      - "3883:3000"
    networks:
      - main
    env_file:
      - path: .env
    environment:
      RAILS_ENV: production
      RAILS_FORCE_SSL: false
      RAILS_ASSUME_SSL: false
    depends_on:
      db:
        condition: service_healthy

  db:
    hostname: maybe_db
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - main
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  main:
    external: true

volumes:
  db-data:
```

**Expected behavior**
The hostname should be properly resolved.

**Screenshots / Recordings**
maybe logs:
![image](https://github.com/maybe-finance/maybe/assets/2727109/42be00f1-134f-4fc7-8fb3-d70886d398dc)
postgres logs:
![image](https://github.com/maybe-finance/maybe/assets/2727109/71e1581b-3473-422c-81ee-46b11d8e7a20)

**Comment by matteogastaldello** [comment] 2024-05-09 20:15
Same here, with default config

**Comment by zachgoll** [comment] 2024-05-09 23:58
For those experiencing this issue, would you mind going through the updated Docker guide that I've opened a PR for and seeing if it fixes this issue for you?

https://github.com/maybe-finance/maybe/blob/zachgoll/docker-improvements/docs/hosting/docker.md

Side note, if you've already created a Postgres volume, you _may_ have to run `docker-compose down -v` to remove the volume (this will delete all existing data!) in order to leverage the default `postgres` user.

**Comment by zachgoll** [comment] 2024-05-10 10:18
Closing this since it is largely a configuration issue that should be addressed by the updated and improved Docker guide and sample compose file:

- Guide - https://github.com/maybe-finance/maybe/blob/main/docs/hosting/docker.md
- New compose file - https://github.com/maybe-finance/maybe/blob/main/docker-compose.example.yml

As for this error specifically, I believe the problem is related to this line:

```
FATAL: database "maybe_production" does not exist
```

The Rails app _defaults_ to the database name, `maybe_production`, so if `POSTGRES_DB` was not explicitly set to this value in the self-hosted setup, you'd get this failure.

The new example file and guide have better defaults to avoid this confusion.

**Closed by zachgoll** 2024-05-10 10:18 UTC
Labels: :bug: Bug
